<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Artifact_Dristribution_Acceptance_Unimatrix</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-07T09:11:19</lastRun>
   <mailRecipient>pg.vishnuqa@gmail.com;poornakiruthikaa@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b9ddd5a1-ea9e-4ea4-b95b-3071855a42bb</testSuiteGuid>
   <testCaseLink>
      <guid>2ff419bb-00c3-44c1-834a-97909e094c80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Artifact_Distribution_Acceptance_Unimatrix/01ArtifactWrite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95624165-686b-48f9-bccf-23593a12ec0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>622e1ffe-bf65-4f88-a657-1f8eeeb660ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Artifact_Distribution_Acceptance_Unimatrix/02Artifact_Read</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd1b51d1-a014-4aa1-b35e-4756ab0e1879</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79422926-bce1-46fb-b06a-eed9a6c6ba2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Artifact_Distribution_Acceptance_Unimatrix/03DistributeArtifact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94a29a34-b82b-47d5-8681-9acb29e62863</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
