<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>QM_Unimatrix_Production</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-07T23:52:34</lastRun>
   <mailRecipient>thomas@sportsrocket.com;eapa@sportsrocket.com;pg.vishnuqa@gmail.com;poornakiruthikaa@gmail.com;qa.angler@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9b2f25a5-d173-40f9-87bf-30c737d1dbca</testSuiteGuid>
   <testCaseLink>
      <guid>f0a6bef0-3177-41a6-bbc6-d00accd389c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QM_Unimatrix_Production/Create_Binary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6179a699-bd09-43aa-b377-fd71894fd04c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a841d13e-cfea-42c2-997f-8a45c5d5bfa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QM_Unimatrix_Production/Create_Binary_Ingressor</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>938771e4-a9b1-4267-bb99-8866e8020a83</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d02ebc8-5caa-4dfb-89bf-e51aa67ffd6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QM_Unimatrix_Production/Read_Check_Binary_Ingressor</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb7ff0af-f69c-4b29-9672-cfa40ec0e2ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e649c98c-4913-4767-916b-e5726d81a453</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QM_Unimatrix_Production/Read_Check_Binary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc3bf73-83fd-42f7-a7c1-d566c2b49227</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce410a01-e38a-4d79-a13a-6b9643805328</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negavite_QM/Create_Binary_Ingressor</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c1bf58d-4f2f-48e5-a508-c0096ed19e34</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
