<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>API_ViewDistributedArtifact</name>
   <tag></tag>
   <elementGuidId>7a9da535-ed0a-49cd-a3d9-a5f977e27ccb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody></httpBody>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uuid</name>
      <type>Main</type>
      <value></value>
   </restParameters>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://us-west-2.distributor.acceptance.boxxspring.net/realms/1e338862026376dd593425404a4f75c0/distributions</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
